import { videoReducer } from "contexts/videoContext/videoReducer";

let initialValue = {
	videos: [
		{
			_id: 1,
			img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
			category: "Crypto",
			title: "",
			description: "",
			creator: "",
			creatorProfile: "",
			views: "",
			videoLength: "",
			youtubeLink: "",
		},
		{
			_id: 2,
			img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
			category: "Blockchain",
			title: "",
			description: "",
			creator: "",
			creatorProfile: "",
			views: "",
			videoLength: "",
			youtubeLink: "",
		},
		{
			_id: 3,
			img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
			category: "Web 3.0",
			title: "",
			description: "",
			creator: "",
			creatorProfile: "",
			views: "",
			videoLength: "",
			youtubeLink: "",
		},
		{
			_id: 4,
			img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
			category: "NFTs",
			title: "",
			description: "",
			creator: "",
			creatorProfile: "",
			views: "",
			videoLength: "",
			youtubeLink: "",
		},
	],
	All: false,
	Crypto: false,
	"Web 3.0": false,
	Blockchain: false,
	NFTs: false,
	filteredVideos: [],
};

describe("Checking video Reducer", () => {
	test("checking type all", () => {
		let expectedData = {
			videos: [
				{
					_id: 1,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Crypto",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 2,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Blockchain",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 3,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Web 3.0",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 4,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "NFTs",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
			],
			All: true,
			Crypto: false,
			"Web 3.0": false,
			Blockchain: false,
			NFTs: false,
			filteredVideos: [
				{
					_id: 1,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Crypto",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 2,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Blockchain",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 3,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Web 3.0",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 4,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "NFTs",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
			],
		};

		let getData = videoReducer(initialValue, { type: "All" });

		expect(getData).toEqual(expectedData);
	});

	test("checking type Crypto", () => {
		let expectedData = {
			videos: [
				{
					_id: 1,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Crypto",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 2,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Blockchain",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 3,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Web 3.0",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 4,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "NFTs",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
			],
			All: false,
			Crypto: true,
			"Web 3.0": false,
			Blockchain: false,
			NFTs: false,
			filteredVideos: [
				{
					_id: 1,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Crypto",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
			],
		};

		let getData = videoReducer(initialValue, { type: "Crypto" });

		expect(getData).toEqual(expectedData);
	});
	test("checking type Blockchain", () => {
		let expectedData = {
			videos: [
				{
					_id: 1,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Crypto",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 2,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Blockchain",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 3,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Web 3.0",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 4,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "NFTs",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
			],
			All: false,
			Crypto: false,
			"Web 3.0": false,
			Blockchain: true,
			NFTs: false,
			filteredVideos: [
				{
					_id: 2,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Blockchain",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
			],
		};

		let getData = videoReducer(initialValue, { type: "Blockchain" });

		expect(getData).toEqual(expectedData);
	});
	test("checking type Web 3.0", () => {
		let expectedData = {
			videos: [
				{
					_id: 1,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Crypto",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 2,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Blockchain",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 3,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Web 3.0",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 4,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "NFTs",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
			],
			All: false,
			Crypto: false,
			"Web 3.0": true,
			Blockchain: false,
			NFTs: false,
			filteredVideos: [
				{
					_id: 3,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Web 3.0",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
			],
		};

		let getData = videoReducer(initialValue, { type: "Web 3.0" });

		expect(getData).toEqual(expectedData);
	});
	test("checking type NFTs", () => {
		let expectedData = {
			videos: [
				{
					_id: 1,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Crypto",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 2,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Blockchain",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 3,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Web 3.0",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 4,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "NFTs",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
			],
			All: false,
			Crypto: false,
			"Web 3.0": false,
			Blockchain: false,
			NFTs: true,
			filteredVideos: [
				{
					_id: 4,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "NFTs",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
			],
		};

		let getData = videoReducer(initialValue, { type: "NFTs" });

		expect(getData).toEqual(expectedData);
	});
	test("checking type Initialize", () => {
		let initialValue = {
			All: false,
			Crypto: false,
			"Web 3.0": false,
			Blockchain: false,
			NFTs: false,
			videos: [],
			filteredVideos: [],
		};

		let expectedData = {
			videos: [
				{
					_id: 1,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Crypto",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 2,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Blockchain",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 3,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Web 3.0",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 4,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "NFTs",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
			],
			All: true,
			Crypto: false,
			"Web 3.0": false,
			Blockchain: false,
			NFTs: false,
			filteredVideos: [
				{
					_id: 1,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Crypto",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 2,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Blockchain",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 3,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Web 3.0",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 4,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "NFTs",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
			],
		};

		let getData = videoReducer(initialValue, {
			type: "Initialize",
			payload: [
				{
					_id: 1,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Crypto",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 2,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Blockchain",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 3,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "Web 3.0",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
				{
					_id: 4,
					img: "https://i.postimg.cc/zBB7Pp3X/thumbnail-01.jpg",
					category: "NFTs",
					title: "",
					description: "",
					creator: "",
					creatorProfile: "",
					views: "",
					videoLength: "",
					youtubeLink: "",
				},
			],
		});

		expect(getData).toEqual(expectedData);
	});
});
